-- 建表
create table public.user_configs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data json null,
  updated_at timestamp with time zone null,
  user_id uuid not null,
  last_device_id text null, -- 1.3.5 新增
  constraint user_configs_pkey primary key (id),
  constraint user_configs_user_id_key unique (user_id)
) TABLESPACE pg_default;

-- 启用行级安全（RLS）
alter table public.user_configs enable row level security;

drop policy if exists "user_configs_select_own" on public.user_configs;
drop policy if exists "user_configs_insert_own" on public.user_configs;
drop policy if exists "user_configs_update_own" on public.user_configs;

create policy "user_configs_select_own"
on public.user_configs
for select
using (auth.uid() = user_id);

create policy "user_configs_insert_own"
on public.user_configs
for insert
with check (auth.uid() = user_id);

create policy "user_configs_update_own"
on public.user_configs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 全量更新函数
create or replace function public.update_user_config_full(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
returns void
language plpgsql
security definer
set search_path = public
as
$$
declare
  current_device_id text;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  insert into public.user_configs (user_id, data, updated_at, last_device_id)
  values (auth.uid(), payload::json, now(), p_last_device_id)
  on conflict (user_id) do update
  set data = excluded.data,
      updated_at = excluded.updated_at,
      last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id);
end;
$$;

grant execute on function public.update_user_config_full(jsonb, text, boolean) to authenticated;
grant execute on function public.update_user_config_full(jsonb, text, boolean) to service_role;

-- 增量更新函数
create or replace function public.update_user_config_partial(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
returns void
language plpgsql
security definer
set search_path = public
as
$$
declare
  current_device_id text;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  update public.user_configs
  set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
      updated_at = now(),
      last_device_id = coalesce(p_last_device_id, last_device_id)
  where user_id = auth.uid();
end;
$$;

grant execute on function public.update_user_config_partial(jsonb, text, boolean) to authenticated;
grant execute on function public.update_user_config_partial(jsonb, text, boolean) to service_role;

-- v1.0.0 版本更新关联板块表

-- 创建 fund_related 表
create table public.fund_related (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fund_code character varying null,
  related_sector text null,
  constraint fund_related_pkey primary key (id),
  constraint fund_related_fund_code_key unique (fund_code)
) TABLESPACE pg_default;

-- 1. 开启 RLS
ALTER TABLE fund_related ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_related"
ON fund_related
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- 创建 fund_secid 表
create table public.fund_secid (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  related_sector text null,
  secid character varying null,
  constraint fund_secid_pkey primary key (id)
) TABLESPACE pg_default;

-- 1. 开启 RLS
ALTER TABLE fund_secid ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_secid"
ON fund_secid
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- v2.1.0 OCR 每日调用次数限流

-- 创建 ocr_daily_usage 表
create table public.ocr_daily_usage (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  usage_date date not null default current_date,
  count int not null default 0,
  constraint ocr_daily_usage_pkey primary key (id),
  constraint ocr_daily_usage_unique unique (user_id, usage_date)
) TABLESPACE pg_default;

alter table public.ocr_daily_usage enable row level security;

-- 允许已登录用户查看自己的用量
create policy "ocr_usage_select_own"
on public.ocr_daily_usage
for select
to authenticated
using (auth.uid() = user_id);

-- 索引加速查询
create index idx_ocr_daily_usage_user_date on public.ocr_daily_usage (user_id, usage_date);

-- 原子检查并自增 OCR 用量的函数
-- 返回: { allowed: boolean, current_count: int, max_limit: int }
create or replace function public.check_and_increment_ocr_usage(
  p_max_limit int default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as
$$
declare
  v_user_id uuid := auth.uid();
  v_today date := current_date;
  v_current_count int;
begin
  if v_user_id is null then
    return jsonb_build_object('allowed', false, 'current_count', 0, 'max_limit', p_max_limit, 'error', 'NOT_AUTHENTICATED');
  end if;

  -- 尝试 upsert 并原子自增
  insert into public.ocr_daily_usage (user_id, usage_date, count)
  values (v_user_id, v_today, 1)
  on conflict (user_id, usage_date)
  do update set count = ocr_daily_usage.count + 1
  where ocr_daily_usage.count < p_max_limit
  returning count into v_current_count;

  -- 如果没有 returning 结果，说明已达上限（WHERE 条件不满足）
  if v_current_count is null then
    select count into v_current_count
    from public.ocr_daily_usage
    where user_id = v_user_id and usage_date = v_today;

    return jsonb_build_object('allowed', false, 'current_count', coalesce(v_current_count, 0), 'max_limit', p_max_limit);
  end if;

  return jsonb_build_object('allowed', true, 'current_count', v_current_count, 'max_limit', p_max_limit);
end;
$$;

grant execute on function public.check_and_increment_ocr_usage(int) to authenticated;
grant execute on function public.check_and_increment_ocr_usage(int) to service_role;
